version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - /app/node_modules
      - ./:/app
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-network
    container_name: aubergineoperations

  nginx:
    build:
      context: ./nginx-dockerfile
      dockerfile: Dockerfile
    ports:
      - 84:85
    networks:
      - app-network
    container_name: nginxwebserver
  client:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 4200:4200
    networks:
      - app-network
    depends_on:
      - server
    container_name: aubergineoperationsfrontend
networks:
  app-network:
    driver: bridge
